[versions]
kotlin = "1.9.21"
clikt = "4.2.1"
xmlutil = "0.86.3"
okio = "3.7.0"
com-kgit2-kommand = "1.2.0"

[libraries]
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version.ref = "clikt" }
xmlutil-core = { group = "io.github.pdvrieze.xmlutil", name = "core", version.ref = "xmlutil" }
xmlutil-serialization = { group = "io.github.pdvrieze.xmlutil", name = "serialization", version.ref = "xmlutil" }
com-squareup-okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
com-kgit2-kommand = { group = "com.kgit2", name = "kommand", version.ref = "com-kgit2-kommand" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
