[versions]
agp = "8.11.0"
burst = "2.5.0"
kotlin = "2.1.20"
clikt = "5.0.3"
okio = "3.10.2"
detekt = "1.23.8"
ksoup = "0.2.2"
maven-publish = "0.31.0"
buildconfig = "5.6.8"
kotlinx-coroutines = "1.10.2"
dokka = "1.9.20"

[libraries]
com-github-ajalt-clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
com-github-ajalt-clikt-markdown = { module = "com.github.ajalt.clikt:clikt-markdown", version.ref = "clikt" }
com-squareup-okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
com-fleeksoft-ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup"}
org-jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
app-cash-burst-gradle-plugin = { module = "app.cash.burst:burst-gradle-plugin", version.ref = "burst" }

# Plugins
org-jetbrains-dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
org-jetbrains-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
org-jetbrains-kotlin-powerAssert-plugin = { module = "org.jetbrains.kotlin:kotlin-power-assert", version.ref = "kotlin" }
com-android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
io-gitlab-arturbosch-detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
com-github-gmazzo-buildconfig-plugin = { module = "com.github.gmazzo.buildconfig:plugin", version.ref = "buildconfig" }
com-vanniktech-gradle-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }
