[versions]
activity-compose = "1.9.1"
agp = "8.6.0"
androidxComposeCompiler = "1.5.10"
compose-bom = "2024.06.00"
core-ktx = "1.13.1"
googleMaterial = "1.12.0"
kotlin = "2.0.0"
lifecycle-runtime-ktx = "2.8.4"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
google-material = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
material3 = { group = "androidx.compose.material3", name = "material3" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]
androidx-compose-ui-debug = ["ui-tooling", "ui-tooling-preview", "ui-test-manifest"]
