name: Build
on: 
  workflow_call:
    inputs:
      target:
        required: true
        type: string
jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ inputs.target }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Prepares environment for building
        uses: ./.github/actions/setup

      - name: Prepare nodeJS enviroment for integrity check
        uses: ./.github/actions/setup-nodejs
        with:
          os: ${{ inputs.target }}

      - name: Cache Kotlin Konan
        id: cache-kotlin-konan
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan/**/*
          key: kotlin-konan-${{ inputs.target }}

      - name: Build Native Binary for macos
        if: inputs.target == 'macos-latest'
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          job-id: ${{ inputs.target }}
          arguments: releaseMacOS

      - name: Build Native Binary for Windows
        if: inputs.target == 'windows-latest'
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          job-id: ${{ inputs.target }}
          arguments: releaseWindows

      - name: Build Native Binary for Linux
        if: inputs.target == 'ubuntu-latest'
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          job-id: ${{ inputs.target }}
          arguments: releaseLinux
