[versions]
activity-compose = "1.9.3"
agp = "8.7.3"
androidxComposeCompiler = "1.5.10"
compose-bom = "2025.01.00"
core-ktx = "1.15.0"
googleMaterial = "1.12.0"
kotlin = "2.1.0"
lifecycle-runtime-ktx = "2.8.7"
s2c = "2.0.1"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
google-material = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
material3 = { group = "androidx.compose.material3", name = "material3" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dev-tonholo-s2c = { id = "dev.tonholo.s2c", version.ref = "s2c" }

[bundles]
androidx-compose-ui-debug = ["ui-tooling", "ui-tooling-preview", "ui-test-manifest"]
